In [1]:
# design a spiral star
import turtle as t
a1 = t.Turtle()
a1.pencolor('red')
for i in range(50):
    a1.forward(i*10)
    a1.left(144)
t.done()


In [2]:
# design  spiral square
import turtle as t
a1 = t.Turtle()
a1.pencolor('red')
for i in range(200):  
    a1.forward(i)
    a1.left(91)
t.done()


Terminator: 

In [5]:
# design  hexagon
from turtle import *
pencolor('red')
colors = ['blue','green','orange','red','yellow','purple']
for i in range(360):
    pencolor(colors[i%6])
    width(i/100+1)
    forward(i)
    left(60)


Terminator: 

In [ ]:
# desig circle
from turtle import *
pensize(20)
pencolor('red')
fillcolor('blue')
begin_fill()
circle(100)
end_fill()


In [ ]:
# desig spiral circle
from turtle import *
pencolor('red')
for i in range(15):
    circle(10*i)

In [ ]:
# design circle
from turtle import *
pencolor('green')
colors = ['blue','green','red','yellow']
for i in range(30):
    pencolor(colors[i%6])
    circle(10*i)
    up()
    sety((10*i)*(-1))
    down()

In [ ]:
# design circle
from turtle import *
r1 = ['blue','green','red','yellow']
for i in range(3):
    penup()
    pencolor(r1[i%3])
    goto(i*100,0)
    pendown()
    circle(45)
r2 = ['','green','','yellow']
for i in range(1,4,2):
    penup()
    pencolor(r2[i])
    goto(i*55,-55)
    pendown()
    circle(50)


# idiomatic python
- transformation code into beautiful, idiomathic python
- replaces traditional index manipulation with python code looping idioms

In [10]:
# looping over a range of numbers
for i in[0,1,2,3,4,5]:
    print(i**2,end=' ')
    
print()
# pythinic-way
for i in range(6):
    print(i** 2,end=' ')

0 1 4 9 16 25 
0 1 4 9 16 25 

In [11]:
# looping over the collection (list)
li = [1,2,3,4,5]
for i in range(len(li)):
    print(li[i],end=' ')
print()
#pythinic-way
for i in li:
    print(i,end=' ')

1 2 3 4 5 
1 2 3 4 5 

In [15]:
# looping from backward s
li = [1,2,3,4,5]
for i in range(len(li)-1,-1,-1):
    print(li[i],end=' ')
print()
# pythonic way
for i in reversed(li):
    print(i,end=' ')

5 4 3 2 1 

In [20]:
# looping over the collection with index
li = [1,2,3,4,5]
for i in range(len(li)):
    print(i,'-->',li[i])
print()
# pytonic way
for i,a in enumerate(li):
    print(i,'-->',a)

0 --> 1
1 --> 2
2 --> 3
3 --> 4
4 --> 5

0 --> 1
1 --> 2
2 --> 3
3 --> 4
4 --> 5


In [21]:
# looping over two collections
li = [1,2,3,4,5]
a = [1,2,3,4,5,6,8]
n = min(len(li),len(a))
for i in range(n):
    print(li[i],' ',a[i])
print()
# pythonic way
for i,a in zip(li,a):
    print(i,' ',a)

1   1
2   2
3   3
4   4
5   5

1   1
2   2
3   3
4   4
5   5


In [25]:
# looping in sorted order
li = [8,1,25,34,9,2]
for i in sorted(li):
    print(i,end=" ")
print()
for i in sorted(li,reverse = True):
    print(i,end = ' ')

1 2 8 9 25 34 
34 25 9 8 2 1 

In [31]:
# dictionary
d = {'name':'gitam','emailid':'gitam@gitam.edu','address':'vizag'}
for k in d:
    print(k,end='  ')
print()

name  emailid  address  


In [34]:
for k in d.keys():
    if k.startswith('a'):
        del d[k]

In [35]:
print(d)

{'name': 'gitam', 'emailid': 'gitam@gitam.edu'}


In [36]:
for k in d.values():
    print(k,end= ' ')

gitam gitam@gitam.edu 

# list comprehension

In [37]:
# traditional approach
li = []
for i in range(10):
    a= i ** 2
    li.append(a)
print(sum(li))
print()
# pythonic way
print(sum(i**2 for i in range(10)))

285

285


In [39]:
li = []
for i in range(10):
    li.append( i** 2)
li

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [2]:
com_list = [i ** 2 for i in range(10)]
com_list

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# lambda functions
- anonymous functions means that a function is without a name
- any lambda function on python will be defined with lambda
- syntax : lambda arg : expression

In [3]:
def square(n):
    return n*n
square(10)

100

In [4]:
a = lambda x : x*x
print(a(10))

100


# use of lambda with filter

In [5]:
def filterlist(li):
    a=[]
    for i in li:
        if i % 2 == 0:
            a.append(i)
    return a
li = [1,2,3,4,5,6,7,8]
filterlist(li)

[2, 4, 6, 8]

In [6]:
li = [1,2,3,4,5,6,7,8]
lam_li = list(filter(lambda x : (x%2==0),li))
print(lam_li)

[2, 4, 6, 8]


### lambda with map()
- map() function in python takes in a function and list as argument

In [8]:
def squarelist(li):
    a =[]
    for i in li:
        a.append(i*2)
    return a
li = [1,2,3,4,5,6,7,8]
squarelist(li)

[2, 4, 6, 8, 10, 12, 14, 16]

In [11]:
li = [1,2,3,4,5,6,7,8]
map_list = list(map(lambda x : x*2,li))
print(map_list)

[2, 4, 6, 8, 10, 12, 14, 16]


# LAMBDA WITH REDUCE()


In [15]:
def sumlist(li):
    s = 0
    for i in li:
        s +=i
    return s
li = [1,2,3,4,5,6,7,8]
sumlist(li)

36

In [17]:
from functools import reduce
li = [1,2,3,4,5,6,7,8]
s = reduce((lambda x,y:x+y),li)
print(s)

36


### standard package
### pandas, numpy and matplotib

###### pandas
### use cases
- data cleaning
- data transformation
- data analysis
### notations
- series
    - A SERIES IS ONE DIMENSIONAL OBJECT THAT CAN HOLD INT,FLOAT AND STRING
- dataframes
    -  A SERIES IS multi DIMENSIONAL OBJECT THAT CAN HOLD INT,FLOAT AND STRING

In [30]:
import pandas as pd
internal1 = {'s1':35,'s2':35,'s3':35}
internal2 = {'s1':35,'s2':35,'s3':35}
internal1 = pd.Series(internal1)
internal2 = pd.Series(internal2)
print(internal1)
print(internal2)
print(type(internal1))

s1    35
s2    35
s3    35
dtype: int64
s1    35
s2    35
s3    35
dtype: int64
<class 'pandas.core.series.Series'>


In [29]:
final = {'internal1':internal1,'internal2':internal2}
final = pd.DataFrame(final)
print(final)
print(type(final))

    internal1  internal2
s1         35         35
s2         35         35
s3         35         35
<class 'pandas.core.frame.DataFrame'>


In [31]:
final.columns # returns the name of columns

Index(['internal1', 'internal2'], dtype='object')

In [32]:
final.values # return all row values in in 2 dimension array

array([[35, 35],
       [35, 35],
       [35, 35]], dtype=int64)

In [35]:
final.values[1]

array([35, 35], dtype=int64)

In [36]:
final.values[2][0] = 350 # update the data frame values

In [37]:
final.values

array([[ 35,  35],
       [ 35,  35],
       [350,  35]], dtype=int64)

In [38]:
for row in final.values:
    print('internal1 - ',row[0],'internal2 - ',row[1])


internal1 -  35 internal2 -  35
internal1 -  35 internal2 -  35
internal1 -  350 internal2 -  35


In [285]:
final.loc['s4'] = [20,18] # inser the ne wrecord intothe data frame
final

internal1  internal2
s1         35         35
s2         35         35
s3        350         35
s4         20         18

In [286]:
final.values[2] = [155,255]
final

internal1  internal2
s1         35         35
s2         35         35
s3        155        255
s4         20         18

In [287]:
pwd

'C:\\Users\\Admin\\Desktop\\problem solving and programming'

In [291]:
filepath = 'datafiles/income.csv'
def readcsvdata(filepath):
    return pd.read_csv(filepath)
df=readcsvdata(filepath)
print(df)

       GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528  


In [292]:
# extract income of all states in year 2020
# alabama : 41381
# ............
for row in df.values:
    print(row[1],' : ',row[-1])

Alabama  :  41381
Alaska  :  61137
Arizona  :  50602
Arkansas  :  39919
California  :  57528


In [293]:
print(df.values)

[['04000US01' 'Alabama' 37150 37952 42212 44476 39980 40933 42590 43464
  41381]
 ['04000US02' 'Alaska' 55891 56418 62993 63989 61604 57848 57431 63648
  61137]
 ['04000US04' 'Arizona' 45245 46657 62993 46914 45739 46896 48621 47044
  50602]
 ['04000US05' 'Arkansas' 36658 37057 40795 39586 36538 38587 41302 39018
  39919]
 ['04000US06' 'California' 51755 55319 55734 57014 56134 54283 53367
  57020 57528]]


In [748]:
# average income of california
def avgofstate():
    s = 0
    for i in range(2,11):
        s+=df.values[4][i]
    return s // len(df.values[4][2:])
avgofstate()

55350

In [749]:
# function which only displays the column names in the list
# GEOID state 2005 2006 2007 2008 2009 2010 2011 2012 2013
def printDataFramecolumns(df):
    li = []
    columns = df.columns
    for i in columns:
        li.append(i)
    return li
printDataFramecolumns(df)

['GEOID',
 'State',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013']

In [752]:
filepath = 'datafiles/regularseasoncompactresults.csv'
def readcsvdata(filepath):
    return pd.read_csv(filepath)
df=readcsvdata(filepath)
print(df)

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0         1985      20   1228      81   1328      64    N      0
1         1985      25   1106      77   1354      70    H      0
2         1985      25   1112      63   1223      56    H      0
3         1985      25   1165      70   1432      54    H      0
4         1985      25   1192      86   1447      74    H      0
5         1985      25   1218      79   1337      78    H      0
6         1985      25   1228      64   1226      44    N      0
7         1985      25   1242      58   1268      56    N      0
8         1985      25   1260      98   1133      80    H      0
9         1985      25   1305      97   1424      89    H      0
10        1985      25   1307     103   1288      71    H      0
11        1985      25   1344      75   1438      71    N      0
12        1985      25   1374      91   1411      72    H      0
13        1985      25   1412      70   1397      65    N      0
14        1985      25   

In [753]:
filepath = 'datafiles/regularseasoncompactresults.csv'
def readcsvdata(filepath):
    return pd.read_csv(filepath)
df=readcsvdata(filepath)

In [754]:
# to know the len of row and col ----shape
df.shape

(145289, 8)

In [755]:
# to know only first few rows -- head()
df.head()

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0

In [756]:
# describe() min,max,count,mean and etc
df.describe()

Season         Daynum          Wteam         Wscore  \
count  145289.000000  145289.000000  145289.000000  145289.000000   
mean     2001.574834      75.223816    1286.720646      76.600321   
std         9.233342      33.287418     104.570275      12.173033   
min      1985.000000       0.000000    1101.000000      34.000000   
25%      1994.000000      47.000000    1198.000000      68.000000   
50%      2002.000000      78.000000    1284.000000      76.000000   
75%      2010.000000     103.000000    1379.000000      84.000000   
max      2016.000000     132.000000    1464.000000     186.000000   

               Lteam         Lscore          Numot  
count  145289.000000  145289.000000  145289.000000  
mean     1282.864064      64.497009       0.044387  
std       104.829234      11.380625       0.247819  
min      1101.000000      20.000000       0.000000  
25%      1191.000000      57.000000       0.000000  
50%      1280.000000      64.000000       0.000000  
75%      1375.000000      72.000000       0.000000  
max      1464.000000     150.000000       6.000000

In [758]:
df.max()

Season    2016
Daynum     132
Wteam     1464
Wscore     186
Lteam     1464
Lscore     150
Wloc         N
Numot        6
dtype: object

In [762]:
df['Lteam'].max()


1464

In [763]:
df['Lteam'].min()


1101

In [765]:
df['Lteam'].sum()

186386037

In [766]:
df.iloc[:3]


Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0

In [769]:
df.sort_values('lscore').tail()
df['lscore'].

SyntaxError: invalid syntax (<ipython-input-769-eb9bc71b65c0>, line 2)

In [773]:
df[(df['Wscore']>170) & (df['Daynum']>60)]

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
17867    1989      92   1258     181   1109     150    H      0
24970    1991      68   1258     186   1109     140    H      0